/**
 * Research Scenarios Matrix (15 Total Scenarios)
 * 8 Legitimate Scenarios (Mandatory False-Positive Protection Tests)
 * 7 Suspicious Scenarios (Attack Patterns)
 */

import { ScenarioDefinition } from '../types/drm';

export const SCENARIOS: ScenarioDefinition[] = [
  // --- 8 LEGITIMATE SCENARIOS ---
  {
    id: 'known_device_new_country',
    name: 'Known Device in New Country',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'An enrolled trusted laptop used while traveling on vacation in Tokyo. IP geo changed from London to Tokyo, but hardware credentials, MFA tokens, and zero auth failures are present.',
    familyContext: 'Account holder on business travel abroad',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 45,
      region_change: true,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.82,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'RULE_FAST_NORMAL',
    },
  },
  {
    id: 'new_device_successful_mfa',
    name: 'New Device with Successful Step-Up MFA',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'User purchased a new iPad in Chennai and successfully completed TOTP step-up authentication during initial enrollment.',
    familyContext: 'Legitimate device upgrade',
    features: {
      trusted_device: false,
      new_device: true,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 20,
      region_change: false,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.78,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'RULE_FAST_NORMAL',
    },
  },
  {
    id: 'different_viewing_schedule',
    name: 'Late-Night Viewing Schedule Shift',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'Trusted living room Smart TV streaming at 03:30 AM (outside habitual 8-10 PM viewing window) on a holiday weekend.',
    familyContext: 'Weekend binge-watching session',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 190,
      region_change: false,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.74,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'RULE_FAST_NORMAL',
    },
  },
  {
    id: 'multi_geo_locations',
    name: 'Multi-Geo Family Usage (London & Dubai)',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'Parent working in Dubai and child studying in London streaming simultaneously on their respective enrolled devices.',
    familyContext: 'Multi-pattern behavioral baseline match',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 2,
      session_duration_min: 60,
      region_change: true,
      impossible_travel: false, // Normal flight separation or distinct persistent devices
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.88,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'RULE_FAST_NORMAL',
    },
  },
  {
    id: 'shared_profile_family',
    name: 'Shared Family Profile (Living Room TV)',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'Smart TV in family residence streaming animated series in afternoon, followed by documentary in evening under the shared family profile.',
    familyContext: 'Shared residential device pattern',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 110,
      region_change: false,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.92,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'RULE_FAST_NORMAL',
    },
  },
  {
    id: 'traveling_user',
    name: 'Commuter on Cellular Network & VPN',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'Trusted smartphone streaming on public railway WiFi with corporate privacy VPN tunnel enabled. Legitimate user, zero auth failures.',
    familyContext: 'Daily commute streaming',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 35,
      region_change: true,
      impossible_travel: false,
      vpn_indicator: true,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.80,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'ML_STAGE', // Privacy VPN goes through Stage 2 ML to verify other signals
    },
  },
  {
    id: 'multiple_trusted_devices',
    name: 'Concurrent Multi-Room Residential Playback',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'Bedroom TV and Living Room Apple TV active concurrently within the same household residential IP.',
    familyContext: 'Dual room viewing in single household',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 2,
      session_duration_min: 75,
      region_change: false,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.95,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'RULE_FAST_NORMAL',
    },
  },
  {
    id: 'normal_baseline',
    name: 'Standard Baseline Home Viewing',
    category: 'Legitimate (False-Positive Validation)',
    expectedLabel: 'Normal (0)',
    description: 'Habitual evening viewing from home location on primary enrolled laptop.',
    familyContext: 'Primary account baseline session',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 50,
      region_change: false,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.98,
    },
    expectedOutcome: {
      expectedLevel: 'LOW',
      expectedAction: 'ALLOW',
      expectedStage: 'RULE_FAST_NORMAL',
    },
  },

  // --- 7 SUSPICIOUS SCENARIOS ---
  {
    id: 'unknown_device_only',
    name: 'Unknown Untrusted Device without MFA',
    category: 'Suspicious (Attack Scenario)',
    expectedLabel: 'Suspicious (1)',
    description: 'Unenrolled browser instance connecting with valid password but lacking trusted device cryptographic enrollment and lacking step-up MFA challenge.',
    features: {
      trusted_device: false,
      new_device: true,
      mfa_success: false,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 10,
      region_change: true,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.45,
    },
    expectedOutcome: {
      expectedLevel: 'MEDIUM',
      expectedAction: 'STEP_UP_MFA',
      expectedStage: 'ML_STAGE',
    },
  },
  {
    id: 'repeated_auth_failures',
    name: 'Credential Stuffing & Auth Failures',
    category: 'Suspicious (Attack Scenario)',
    expectedLabel: 'Suspicious (1)',
    description: 'Five consecutive incorrect password attempts followed by successful login from an unfamiliar IP range.',
    features: {
      trusted_device: false,
      new_device: true,
      mfa_success: false,
      auth_failures: 5,
      concurrent_sessions: 1,
      session_duration_min: 5,
      region_change: true,
      impossible_travel: false,
      vpn_indicator: true,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.20,
    },
    expectedOutcome: {
      expectedLevel: 'HIGH',
      expectedAction: 'RESTRICT_STREAM',
      expectedStage: 'RULE_FAST_BAD',
    },
  },
  {
    id: 'impossible_travel',
    name: 'Impossible Physical Travel Velocity',
    category: 'Suspicious (Attack Scenario)',
    expectedLabel: 'Suspicious (1)',
    description: 'Active streaming session started in Chennai, India, followed 4 minutes later by session start on untrusted device in London, UK.',
    features: {
      trusted_device: false,
      new_device: true,
      mfa_success: false,
      auth_failures: 2,
      concurrent_sessions: 2,
      session_duration_min: 8,
      region_change: true,
      impossible_travel: true,
      vpn_indicator: true,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.15,
    },
    expectedOutcome: {
      expectedLevel: 'HIGH',
      expectedAction: 'RESTRICT_STREAM',
      expectedStage: 'RULE_FAST_BAD',
    },
  },
  {
    id: 'excessive_concurrency',
    name: 'Credential Reselling / Pirate Restream Multiplex',
    category: 'Suspicious (Attack Scenario)',
    expectedLabel: 'Suspicious (1)',
    description: 'Eight concurrent streams simultaneously running across disparate geographic hosting providers on unenrolled clients.',
    features: {
      trusted_device: false,
      new_device: true,
      mfa_success: false,
      auth_failures: 1,
      concurrent_sessions: 8,
      session_duration_min: 300,
      region_change: true,
      impossible_travel: false,
      vpn_indicator: true,
      playback_anomaly: true,
      capture_indicator: false,
      historical_consistency: 0.10,
    },
    expectedOutcome: {
      expectedLevel: 'HIGH',
      expectedAction: 'RESTRICT_STREAM',
      expectedStage: 'RULE_FAST_BAD',
    },
  },
  {
    id: 'sudden_device_churn',
    name: 'Rapid Device Fingerprint Churn',
    category: 'Suspicious (Attack Scenario)',
    expectedLabel: 'Suspicious (1)',
    description: 'Continuous cycling through random user-agent fingerprints and headless browser identifiers within seconds.',
    features: {
      trusted_device: false,
      new_device: true,
      mfa_success: false,
      auth_failures: 3,
      concurrent_sessions: 2,
      session_duration_min: 2,
      region_change: true,
      impossible_travel: false,
      vpn_indicator: true,
      playback_anomaly: false,
      capture_indicator: false,
      historical_consistency: 0.18,
    },
    expectedOutcome: {
      expectedLevel: 'HIGH',
      expectedAction: 'RESTRICT_STREAM',
      expectedStage: 'RULE_FAST_BAD',
    },
  },
  {
    id: 'multi_anomaly_attack',
    name: 'Coordinated Multi-Vector Attack',
    category: 'Suspicious (Attack Scenario)',
    expectedLabel: 'Suspicious (1)',
    description: 'Impossible travel velocity + active capture API hooks + failed password history on headless server IP.',
    features: {
      trusted_device: false,
      new_device: true,
      mfa_success: false,
      auth_failures: 4,
      concurrent_sessions: 3,
      session_duration_min: 15,
      region_change: true,
      impossible_travel: true,
      vpn_indicator: true,
      playback_anomaly: true,
      capture_indicator: true,
      historical_consistency: 0.05,
    },
    expectedOutcome: {
      expectedLevel: 'HIGH',
      expectedAction: 'RESTRICT_STREAM',
      expectedStage: 'RULE_FAST_BAD',
    },
  },
  {
    id: 'suspicious_capture_indicator',
    name: 'Hardware Surface Screen Capture Tool Detected',
    category: 'Suspicious (Attack Scenario)',
    expectedLabel: 'Suspicious (1)',
    description: 'Client-side DRM integrity monitor detected direct DXGI/MediaProjection capture surface hook attempting to record video buffer.',
    features: {
      trusted_device: true,
      new_device: false,
      mfa_success: true,
      auth_failures: 0,
      concurrent_sessions: 1,
      session_duration_min: 40,
      region_change: false,
      impossible_travel: false,
      vpn_indicator: false,
      playback_anomaly: false,
      capture_indicator: true,
      historical_consistency: 0.65,
    },
    expectedOutcome: {
      expectedLevel: 'MEDIUM',
      expectedAction: 'STEP_UP_MFA', // Proportional: doesn't kill immediately on first screen hook; strengthens watermark + triggers step-up
      expectedStage: 'ML_STAGE',
    },
  },
];
